# Generated by Django 5.2.2 on 2025-08-13 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction_bids_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='imageURL',
            field=models.CharField(blank=True),
        ),
    ]
