# Generated by Django 5.2.2 on 2025-08-16 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auction_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='startingBid',
            field=models.FloatField(),
        ),
    ]
