# Generated by Django 5.2.2 on 2025-08-19 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_rename_auction_auctions_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctions',
            name='createdBy',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='auctions', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auctions',
            name='current_price',
            field=models.FloatField(default=3),
            preserve_default=False,
        ),
    ]
