# Generated by Django 5.2.2 on 2025-08-20 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auctions_createdby_auctions_current_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctions',
            name='number_of_bids',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bids',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bids',
            name='auction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auctions.auctions'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bids',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='user_bids', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
