# Generated by Django 5.2.2 on 2025-08-20 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auctions_number_of_bids_bids_amount_bids_auction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctions',
            name='number_of_bids',
            field=models.IntegerField(),
        ),
    ]
