# Generated by Django 5.2.2 on 2025-08-20 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_alter_auctions_number_of_bids'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctions',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='auctions',
            name='number_of_bids',
            field=models.IntegerField(default=0),
        ),
    ]
