# Generated by Django 5.2.2 on 2025-08-21 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_comments_auction_comments_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='comment',
            field=models.CharField(default=0),
            preserve_default=False,
        ),
    ]
